config/routes.rb
if CANVAS_RAILS2
  # Even on Rails 2.3, we're using Rails 3 style routes.
  #
  # You should have plenty of examples in here for anything you're trying to do,
  # but if you want a full primer this is a good one:
  # http://blog.engineyard.com/2010/the-lowdown-on-routes-in-rails-3
  #
  # Don't try anything too fancy, FakeRails3Routes doesn't support some of the
  # more advanced Rails 3 routing features, since in the background it's just
  # calling into the Rails 2 routing system.
  routes = FakeRails3Routes
else
  routes = CanvasRails::Application.routes
end

routes.draw do
  resources :submission_comments, :only => :destroy

  match 'inbox' => 'context#mark_inbox_as_read', :as => :mark_inbox_as_read, :via => :delete
  match 'inbox' => 'context#inbox', :as => :inbox
  match 'inbox/:id' => 'context#destroy_inbox_item', :as => :destroy_inbox_item, :via => :delete
  match 'inbox/:id' => 'context#inbox_item', :as => :inbox_item

  match 'conversations/discussion_replies' => 'context#discussion_replies', :as => :discussion_replies
  match 'conversations/unread' => 'conversations#index', :as => :conversations_unread, :redirect_scope => 'unread'
  match 'conversations/starred' => 'conversations#index', :as => :conversations_starred, :redirect_scope => 'starred'
  match 'conversations/sent' => 'conversations#index', :as => :conversations_sent, :redirect_scope => 'sent'
  match 'conversations/archived' => 'conversations#index', :as => :conversations_archived, :redirect_scope => 'archived'
  match 'conversations/find_recipients' => 'search#recipients'

  match 'search/recipients' => 'search#recipients', :as => :search_recipients
  match 'conversations/mark_all_as_read' => 'conversations#mark_all_as_read', :as => :conversations_mark_all_as_read, :via => :post
  match 'conversations/watched_intro' => 'conversations#watched_intro', :as => :conversations_watched_intro, :via => :post
  match 'conversations/batches' => 'conversations#batches', :as => :conversation_batches
  match 'conversations/toggle_new_conversations' => 'conversations#toggle_new_conversations', :as => :toggle_new_conversations, :via => :post
  resources :conversations, :only => [:index, :show, :update, :create, :destroy] do
    match 'add_recipients' => 'conversations#add_recipients', :as => :add_recipients, :via => :post
    match 'add_message' => 'conversations#add_message', :as => :add_message, :via => :post
    match 'remove_messages' => 'conversations#remove_messages', :as => :remove_messages, :via => :post
  end

  # So, this will look like:
  # http://instructure.com/register/5R32s9iqwLK75Jbbj0
  match 'register/:nonce' => 'communication_channels#confirm', :as => :registration_confirmation
  # deprecated
  match 'pseudonyms/:id/register/:nonce' => 'communication_channels#confirm', :as => :registration_confirmation_deprecated
  match 'confirmations/:user_id/re_send/:id' => 'communication_channels#re_send_confirmation', :as => :re_send_confirmation, :id => nil
  match 'forgot_password' => 'pseudonyms#forgot_password', :as => :forgot_password
  match 'pseudonyms/:pseudonym_id/change_password/:nonce' => 'pseudonyms#confirm_change_password', :as => :confirm_change_password, :via => :get
  match 'pseudonyms/:pseudonym_id/change_password/:nonce' => 'pseudonyms#change_password', :as => :change_password, :via => :post

  # callback urls for oauth authorization processes
  match 'oauth' => 'users#oauth', :as => :oauth
  match 'oauth_success' => 'users#oauth_success', :as => :oauth_success

  match 'mr/:id' => 'info#message_redirect', :as => :message_redirect
  match 'help_links' => 'info#help_links', :as => :help_links

  concern :question_banks do
    resources :question_banks do
      match 'bookmark' => 'question_banks#bookmark', :as => :bookmark
      match 'reorder' => 'question_banks#reorder', :as => :reorder
      match 'questions' => 'question_banks#questions', :as => :questions
      match 'move_questions' => 'question_banks#move_questions', :as => :move_questions
      resources :assessment_questions
    end
  end

  concern :groups do
    resources :groups
    resources :group_categories, :only => [:create, :update, :destroy]
    match 'group_unassigned_members' => 'groups#unassigned_members', :as => :group_unassigned_members, :via => :get
  end

  concern :files do
    resources :files do
      match 'inline' => 'files#text_show', :as => :text_inline
      match 'download' => 'files#show', :as => :download, :download => '1'
      match 'download.:type' => 'files#show', :as => :typed_download, :download => '1'
      match 'preview' => 'files#show', :as => :preview, :preview => '1'
      match 'inline_view' => 'files#show', :as => :inline_view, :inline => '1'
      match 'scribd_render' => 'files#scribd_render', :as => :scribd_render
      match 'contents' => 'files#attachment_content', :as => :attachment_content
      match ':file_path' => 'files#show_relative', :as => :relative_path, :file_path => /.+/
      collection do
        get :quota
        post :reorder
      end
    end
  end

  concern :file_images do
    match 'images' => 'files#images', :as => :images
  end

  concern :relative_files do
    match 'file_contents/:file_path' => 'files#show_relative', :as => :relative_file_path, :file_path => /.+/
  end

  concern :folders do
    resources :folders do
      match 'download' => 'folders#download', :as => :download
    end
  end

  concern :media do
    match 'media_download' => 'users#media_download', :as => :media_download
    match 'media_download.:type' => 'users#media_download', :as => :typed_media_download
  end

  concern :users do
    match 'users' => 'context#roster', :as => :users
    match 'user_services' => 'context#roster_user_services', :as => :user_services
    match 'users/:user_id/usage' => 'context#roster_user_usage', :as => :user_usage
    match 'users/:id' => 'context#roster_user', :as => :user, :via => :get
  end

  concern :announcements do
    resources :announcements
    match 'announcements/external_feeds' => 'announcements#create_external_feed', :as => :announcements_external_feeds, :via => :post
    match 'announcements/external_feeds/:id' => 'announcements#destroy_external_feed', :as => :announcements_external_feed, :via => :delete
  end

  concern :discussions do
    resources :discussion_topics, :only => [:index, :new, :show, :edit, :destroy]
    match 'discussion_topics/:id/:extras' => 'discussion_topics#show', :as => :map, :extras => /.+/
    resources :discussion_entries
  end

  concern :wikis do
    ####
    ## Leaving these routes here for when we need them later :)
    ##
    ## Aside from the /wiki route itself, all new routes will be /pages. The /wiki route will be reused to redirect
    ## the user to the wiki front page, if configured, or the wiki page list otherwise.
    ####
    # match 'wiki' => 'wiki_pages#front_page', :via => :get, :as => :wiki

    ####
    ## Placing these routes above the /wiki routes below will cause the helper functions to generate urls and paths
    ## pointing to /pages rather than the legacy /wiki.
    ####
    # resources :wiki_pages, :path => :pages do
    #   match 'revisions/latest' => 'wiki_page_revisions#latest_version_number', :as => :latest_version_number
    #   resources :wiki_page_revisions, :as => "revisions"
    # end
    #
    ####
    ## We'll just do specific routes below until we can swap /pages and /wiki completely.
    ####
    get 'pages' => 'wiki_pages#pages_index'
    get 'pages/:wiki_page_id' => 'wiki_pages#show_page', :wiki_page_id => /[^\/]+/, :as => :named_page
    get 'pages/:wiki_page_id/edit' => 'wiki_pages#edit_page', :wiki_page_id => /[^\/]+/, :as => :edit_named_page
    get 'pages/:wiki_page_id/revisions' => 'wiki_pages#page_revisions', :wiki_page_id => /[^\/]+/, :as => :named_page_revisions

    resources :wiki_pages, :path => :wiki do
      match 'revisions/latest' => 'wiki_page_revisions#latest_version_number', :as => :latest_version_number
      resources :wiki_page_revisions, :path => :revisions
    end

    ####
    ## This will cause the helper functions to generate /pages urls, but will still allow /wiki routes to work properly
    ####
    #match 'pages/:id' => 'wiki_pages#show', :id => /[^\/]+/, :as => :named_wiki_page

    match 'wiki/:id' => 'wiki_pages#show', :as => :named_wiki_page, :id => /[^\/]+/
  end

  concern :conferences do
    resources :conferences do
      match 'join' => 'conferences#join', :as => :join
      match 'close' => 'conferences#close', :as => :close
      match 'settings' => 'conferences#settings', :as => :settings
    end
  end

  concern :zip_file_imports do
    resources :zip_file_imports, :only => [:new, :create, :show]
    match 'imports/files' => 'content_imports#files', :as => :import_files
  end

  # There are a lot of resources that are all scoped to the course level
  # (assignments, files, wiki pages, user lists, forums, etc.).  Many of
  # these resources also apply to groups and individual users.  We call
  # courses, users, groups, or even accounts in this setting, "contexts".
  # There are some helper methods like the before_filter :get_context in application_controller
  # and the application_helper method :context_url to make retrieving
  # these contexts, and also generating context-specific urls, easier.
  resources :courses do
    # DEPRECATED
    match 'self_enrollment/:self_enrollment' => 'courses#self_enrollment', :as => :self_enrollment, :via => :get
    match 'self_unenrollment/:self_unenrollment' => 'courses#self_unenrollment', :as => :self_unenrollment, :via => :post
    match 'restore' => 'courses#restore', :as => :restore
    match 'backup' => 'courses#backup', :as => :backup
    match 'unconclude' => 'courses#unconclude', :as => :unconclude
    match 'students' => 'courses#students', :as => :students
    match 'enrollment_invitation' => 'courses#enrollment_invitation', :as => :enrollment_invitation

app/models/pseudonym_session.rb
#
# Copyright (C) 2011 Instructure, Inc.
#
# This file is part of Canvas.
#
# Canvas is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.
#

class PseudonymSession < Authlogic::Session::Base
  last_request_at_threshold  10.minutes
  verify_password_method :valid_arbitrary_credentials?
  login_field :unique_id
  find_by_login_method :custom_find_by_unique_id
  remember_me_for 2.weeks

  attr_accessor :remote_ip, :too_many_attempts

  # we need to know if the session came from http basic auth, so we override
  # authlogic's method here to add a flag that we can check
  def persist_by_http_auth
    controller.authenticate_with_http_basic do |login, password|
      if !login.blank? && !password.blank?
        send("#{login_field}=", login)
        send("#{password_field}=", password)
        @valid_basic_auth = valid?
        return @valid_basic_auth
      end
    end

    false
  end
  def used_basic_auth?
    @valid_basic_auth
  end

  unless CANVAS_RAILS2
    # In authlogic 3.2.0, it tries to parse the last part of the cookie (delimited by '::')
    # as a timestamp to verify whether the cookie is stale.
    # This conflicts with the uuid that we use instead in that place,
    # so skip that check for now, to keep behavior similar between Rails 2 and 3.
    def remember_me_expired?
      false
    end
  end

  if CANVAS_RAILS2
    # modifications to authlogic's cookie persistence (used for the "remember me" token)
    # see the SessionPersistenceToken class for details
    #
    # also, the version of authlogic canvas is on doesn't support httponly (or
    # secure-only) for the "remember me" cookie yet, so we add that support here.
    def save_cookie
      return unless remember_me?
      token = SessionPersistenceToken.generate(record)
      controller.cookies[cookie_key] = {
        :value => token.pseudonym_credentials,
        :expires => remember_me_until,
        :domain => controller.cookie_domain,
        :httponly => true,
        :secure => controller.request.session_options[:secure],
      }
    end
  else
    secure CanvasRails::Application.config.session_options[:secure]
    httponly true

    # modifications to authlogic's cookie persistence (used for the "remember me" token)
    # see the SessionPersistenceToken class for details
    def save_cookie
      return unless remember_me?
      token = SessionPersistenceToken.generate(record)
      controller.cookies[cookie_key] = {
        :value => token.pseudonym_credentials,
        :expires => remember_me_until,
        :domain => controller.cookie_domain,
        :httponly => httponly,
        :secure => secure,
      }
    end
  end

  def persist_by_cookie
    cookie = controller.cookies[cookie_key]
    if cookie
      token = SessionPersistenceToken.find_by_pseudonym_credentials(cookie)
      self.unauthorized_record = token.use! if token
      is_valid = self.valid?
      if is_valid
        # this token has been used -- destroy it, and generate a new one
        # remember_me is implicitly true when they login via the remember_me token
        controller.session[:used_remember_me_token] = true
        self.remember_me = true
        self.save!
      end
      is_valid
    else
      false
    end
  end

  # added behavior: destroy the server-side SessionPersistenceToken as well as the browser cookie
  def destroy_cookie
    cookie = controller.cookies.delete cookie_key, :domain => controller.cookie_domain
    return true unless cookie
    token = SessionPersistenceToken.find_by_pseudonym_credentials(cookie)
    token.try(:destroy)
    true
  end

  # Validate the session using password auth (either local or LDAP, but not
  # SSO). If too many failed attempts have occured, the validation will fail.
  # In this case, `too_many_attempts?` will be true, rather than
  # `invalid_password?`.
  #
  # Note that for IP based max attempt tracking to occur, you'll need to set
  # remote_ip on the PseudonymSession before calling save/valid?. Otherwise,
  # only total # of failed attempts will be tracked.
  def validate_by_password
    super

    # have to call super first, as that's what loads attempted_record
    if too_many_attempts? || attempted_record.try(:audit_login, remote_ip, !invalid_password?) == :too_many_attempts
      self.too_many_attempts = true
      errors.add(password_field, I18n.t('errors.max_attempts', 'Too many failed login attempts. Please try again later or contact your system administrator.'))
      return
    end
  end

  def too_many_attempts?
    too_many_attempts == true
  end
end

app/helpers/pseudonym_sessions_helper.rb
#
# Copyright (C) 2011 Instructure, Inc.
#
# This file is part of Canvas.
#
# Canvas is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.
#

module PseudonymSessionsHelper
  def session_timeout_enabled
    PluginSetting.settings_for_plugin 'sessions'
  end
end

app/views/pseudonym_sessions/mobile_login.html.erb
<%= form_for :pseudonym_session, :url => login_path, :html => {:id => "login_form", :class => "front face", :novalidate => 'novalidate'} do |f| %>
  <input class="input-block-level" <%= 'type=email' if @login_handle_is_email %> name="pseudonym_session[unique_id]" value="<%= params[:pseudonym_session].try(:[], :unique_id) %>" placeholder="<%= @login_handle_name %>">
  <input class="input-block-level" type="password" name="pseudonym_session[password]" placeholder="<%= t :password, "Password" %>">
  <% if request.post? && flash[:error] %>
    <div class="error"><%= flash[:error] %></div>
  <% end %>
  <button type="submit" class="btn btn-primary btn-large"><%= t('login', 'Login') %></button>
  <% if url = params[:canvas_login].blank? && @domain_root_account.try(:forgot_password_external_url) %>
    <%= link_to t('dont_know_password', "I don't know my password"), url, :class => 'btn btn-large forgot-password' %>
  <% else %>
    <a class="btn btn-large btn-inverse flip-to-back"><%= t('dont_know_password', "I don't know my password") %></a>
  <% end %>
<% end %>
<%= form_for :pseudonym_session, :url => forgot_password_path, :html => {:id => "forgot_password_form", :class => 'back face'} do |f| %>
  <label for="pseudonym_session_unique_id_forgot"><%= t('login_handle', "Enter your %{login_handle_name} and we'll send you a link to change your password.", :login_handle_name => @login_handle_name) %></label>
  <input class="input-block-level" <%= 'type=email' if @login_handle_is_email %> name="pseudonym_session[unique_id_forgot]" value="<%= @unauthorized_user.try :email %>" placeholder="<%= @login_handle_name %>" id="pseudonym_session_unique_id_forgot" />
  <button type="submit" class="btn btn-primary btn-large" data-text-while-loading="<%= t :sending, "Sending..." %>" class="request-password-button"><%= t('buttons.request_password', 'Request Password') %></button>
  <a class="btn btn-large btn-inverse flip-to-front"><%= t('back_to_login', "Back to Login") %></a>
<% end %>
<%= # for plugin use
  render "shared/login_trailer" %>

<script>
  var eventToBindTo = ('ontouchstart' in window) ? 'touchstart' : 'click';

  document.addEventListener('DOMContentLoaded', function(){
    var $front_back_container = document.querySelector('#f1_container'),
        $flip_to_back         = document.querySelector('.flip-to-back');

    if ($flip_to_back) {
      $flip_to_back.addEventListener(eventToBindTo, function(event){
        event.preventDefault();
        addClass($front_back_container, 'flipped');
      });
    }

    document.querySelector('.flip-to-front').addEventListener(eventToBindTo, function(event){
      event.preventDefault();
      removeClass($front_back_container, 'flipped');
    });

    var $forgot_password_form = document.querySelector('#forgot_password_form');
    $forgot_password_form.addEventListener('submit', function(event){
      var $button      = $forgot_password_form.querySelector('.request-password-button'),
          originalText = $button.textContent,
          uniqueId     = $forgot_password_form.querySelector('input[name="pseudonym_session[unique_id_forgot]"]').value.trim();
      if (!uniqueId) return false;
      $button.disabled = true;
      $button.textContent = $button.getAttribute('data-text-while-loading')
      event.preventDefault();
      ajax({
        type: "POST",
        url: "/forgot_password",
        data: 'authenticity_token=' +
              encodeURIComponent($forgot_password_form.querySelector('input[name=authenticity_token]').value) +
              '&pseudonym_session%5Bunique_id_forgot%5D=' +
              encodeURIComponent(uniqueId),
        success: function(response){
          alert(ENV.RESET_SENT);
        },
        error: function(){
          alert(ENV.RESET_ERROR);
        },
        complete: function(){
          $button.textContent = originalText;
        }
      });
    });
  });

  function addClass(element, name){
    removeClass(element, name);
    element.className += ' ' + name;
  }

  function removeClass(element, name){
    regex = new RegExp('(^|\\s)' + name + '(\\s|$)');
    element.className = element.className.replace(regex, '')
  }

  function ajax(options){
    var xhr = new window.XMLHttpRequest();
    options.headers = options.headers || {}
    options.headers['X-Requested-With'] = 'XMLHttpRequest'
    if (options.data && !options.contentType) options.contentType = 'application/x-www-form-urlencoded';
    if (options.contentType) options.headers['Content-Type'] = options.contentType;

    xhr.onreadystatechange = function(){
      if (xhr.readyState == 4) {
        var error = false;
        if ((xhr.status >= 200 && xhr.status < 300) || xhr.status == 0) {
          options.success && options.success.call(options.context, xhr.responseText, 'success', xhr);
        } else {
          error = true;
          options.error && options.error.call(options.context, xhr, 'error');
        }
        options.complete && options.complete.call(options.context, xhr, error ? 'error' : 'success');
      }
    };

    xhr.open(options.type, options.url, true);
    for (name in options.headers) xhr.setRequestHeader(name, options.headers[name]);
    xhr.send(options.data);
    return xhr;
  }
</script>

app/views/pseudonym_sessions/new.html.erb
<% content_for :page_title do %>
  <%= t :page_title, "Log In to Canvas" %>
<% end %>

<%= render :partial => "shared/login" %>
<% if flash[:logged_out] && HostUrl.file_host(@domain_root_account, @request.host_with_port) %>
  <img class="hidden-readable" src="//<%= HostUrl.file_host(@domain_root_account, @request.host_with_port) %>/file_session/clear"/>
<% end %>

app/views/pseudonym_sessions/oauth2_auth.html.erb
<%# normally the native application will intercept the redirect and this will never be seen, this is just a failsafe %>
<%= t 'oauth2_complete', 'The application has finished the login workflow, and should reactivate shortly.' %>

app/views/pseudonym_sessions/oauth2_confirm.html.erb
<%
  jammit_css :login
  @headers = false
  @body_classes << "modal"
  content_for :page_title, t(:page_title, "App Login")
%>
<div id="modal-box">
  <h2>
    <% if @provider.icon_url %>
      <%= image_tag @provider.icon_url, :alt => '', :class => 'icon_url' %>
    <% end %>
    <%= @provider.app_name %>
  </h2>
  <p>
  <%= mt 'details.allow_application', "%{app_name} is requesting access to your account.", :app_name => @provider.app_name %>
    <br/><br/>
    <%= mt 'details.login_name', "You are logging into this app as %{user_name}.", :user_name => link_to(@current_user.short_name, user_profile_url(@current_user), :popup => true) %>
    <% if @current_user.email.present? && @current_user.email != @current_user.short_name %>
      <br/>
      <%= t 'details.email', "Your email address is %{email}.", :email => @current_user.email %>
    <% end %>
  </p>
  <%= form_tag oauth2_auth_accept_path do %>
    <div class="button_box">
      <%= link_to(t(:cancel, "Cancel"), oauth2_auth_deny_path, :class => "btn") %>
      <%=  submit_tag("Log in",  :class => "btn btn-primary") %>
    </div>
    <% unless @provider.scopes.blank? %>
      <div class="control-group">
        <%= check_box_tag(:remember_access, "1", false, :class => "checkbox") %>
        <%= label_tag(:remember_access, :en => "Remember my authorization for this service", :class => "checkbox") %>
      </div>
    <% end %>
<% end %>
</div>

app/views/pseudonym_sessions/oauth2_confirm_mobile.html.erb
<%
  content_for :page_title, t(:page_title, "App Login")
%>
<div class="face">
  <h2><%= @provider.app_name %></h2>
  <p>
  <%= mt 'details.allow_application', "%{app_name} is requesting access to your account.", :app_name => @provider.app_name %>
    <br/><br/>
    <%= mt 'details.login_name', "You are logging into this app as %{user_name}.", :user_name => link_to(@current_user.short_name, user_profile_url(@current_user), :popup => true) %>
    <% if @current_user.email.present? && @current_user.email != @current_user.short_name %>
      <br/>
      <%= t 'details.email', "Your email address is %{email}.", :email => @current_user.email %>
    <% end %>
  </p>
  <%= form_tag oauth2_auth_accept_path do %>
    <div class="button_box">
      <button type="submit" class="btn btn-large btn-primary"><%= t 'login', 'Log In' %></button>
      <%= link_to(t(:cancel, "Cancel"), oauth2_auth_deny_path, :class => "btn btn-large") %>
    </div>
    <% if true#unless @provider.scopes.blank? %>
      <div class="control-group">
        <label class="checkbox" for="remember_access">
          <%= check_box_tag(:remember_access, "1", false, :class => "checkbox") %>
          <%= t 'remember_auth', 'Remember my authorization for this service' %>
        </label>
      </div>
    <% end %>
<% end %>
</div>

app/views/pseudonym_sessions/otp_login.html.erb
<%
  jammit_css :otp_login
  js_bundle :otp_login
  @headers = false
  @body_classes << "modal"
  content_for :page_title, t(:page_title, "Multi-factor Authentication")
%>

<% content_for :meta_tags do %>
  <meta name="viewport" id="vp" content="initial-scale=1.0,user-scalable=yes,width=device-width">
<% end %>

<div id="modal-box">
  <h2><%= t 'titles.mfa', "Multi-factor Authentication" %></h2>
  <% if session[:pending_otp_secret_key] %>
    <div>
      <% if @current_user.mfa_settings == :required %>
        <p><%= t('details.mfa_required', "You are required to set up multi-factor authentication.") %></p>
      <% end %>
      <p><%=  mt('details.mfa_enrollment', <<-BODY, :secret_key => session[:pending_otp_secret_key], :iphone_url => 'http://itunes.apple.com/us/app/google-authenticator/id388497605', :android_url => 'https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2')
Multi-factor authentication increases security by requiring that you have something in your physical possession,
in addition to knowing your password, in order to log in to Canvas. This can be a device that can generate
verification codes, or a phone that can receive text messages. The Google Authenticator app for [iPhone](%{iphone_url}) or
[Android](%{android_url}) can be configured by scanning the QR Code below. Other tokens can be configured by entering the
secret key **%{secret_key}**.
          BODY
      %></p>

      <div class="row-fluid">
        <div class="span8">
          <% ccs = @current_user.communication_channels.sms.unretired.map { |cc| [ cc.path, cc.id ] } %>
          <% unless ccs.empty? %>
            <% ccs << [ "<< #{t('select.new_number', "a new phone")} >>", '{{id}}' ] %>
            <%= form_for :otp_login, :url => otp_login_path, :html => {:id => 'select_phone_form'} do |f| %>
              <%= t('details.send_to_sms', "Send text messages to %{phone_number}", :phone_number => f.select('otp_communication_channel_id', ccs, :selected => @cc.try(:id))) %>
              <button type="submit" class="btn btn-primary"><%= t('buttons.send', "Send") %></button>
            <% end %>
          <% end %>
          <%= form_for :otp_login, :url => otp_login_path, :html => { :id => 'new_phone_form', :style => (hidden(false) unless ccs.empty?), :class => 'bootstrap-form form-horizontal' } do |f| %>
            <div class="control-group">
              <%= f.blabel :phone_number, :en => 'Phone Number', :class => 'control-label' %>
              <div class="controls"><%= f.text_field :phone_number, :class => 'input-medium' %></div>
            </div>
            <div class="control-group">
              <%= f.blabel :carrier, :en => 'Carrier', :class => 'control-label' %>
              <div class="controls"><%= f.select :carrier, CommunicationChannel.sms_carriers, {}, { :style => 'width: 100%' } %></div>
            </div>
            <div class="control-group">
              <div class="controls">
                <button type="submit" class="btn btn-primary"><%= t('buttons.send', "Send") %></button>
                <% unless ccs.empty? %>
                  <br />
                    <a href="#" id="back_to_choose_number_link"><%= t('links.choose_number', "Choose an existing phone") %></a>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
        <div class="span4" style="text-align: center">
          <% provisioning_uri = ROTP::TOTP.new(session[:pending_otp_secret_key]).provisioning_uri("Canvas") %>
          <% qr_code = Barby::QrCode.new(provisioning_uri) %>
          <img src="data:image/png;base64,<%= Base64.encode64(qr_code.to_png(:xdim => 4)).strip %>">
        </div>
      </div>
    </div>
  <% end %>

  <p></p>
  <% if @cc %>
    <div><p><%= t('details.otp_sent_to_phone', "A verification code has been sent to your phone. Please enter it here.") %></p></div>
  <% else %>
    <div><p><%= t('details.otp_on_device', "Please enter the verification code shown by your token.") %></p></div>
  <% end %>
  <%= form_for :otp_login, :url => otp_login_path, :html => {:id => "login_form", :class => "inline-form"} do |f| %>
    <div>
      <%= f.blabel :verification_code, :en => "Verification Code", :class => 'control-label' %>
      <%= f.text_field :verification_code, :class => "text", :autocomplete => 'off' %>
      <button type="submit" class="btn btn-primary"><%= t('buttons.verify', 'Verify') %></button>
    </div>
    <div>
      <%= f.check_box :remember_me %> <%= f.label :remember_me, :en => "Remember this computer" %>
    </div>
  <% end %>
</div>